# .cpanel.yml
---
deployment:
  tasks:
    - /usr/bin/git -C /home/wkkgb451/repositories/Asgaria pull origin live
    - cd /home/wkkgb451/repositories/Asgaria && npm install
    - mkdir -p /home/wkkgb451/repositories/Asgaria/tmp
    - touch /home/wkkgb451/repositories/Asgaria/tmp/restart.txt
